#sudo: false
#dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - build-essential
      - libsdl1.2-dev
      - libbz2-dev
      - zlib1g-dev
      - liblua5.1-0-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - scons
      - libfftw3-dev
      - python
script:
  - scons --lin --sse2 --64bit -j3
